#### Tensor 이해

In [2]:
### 모듈 로딩
import torch 

- Tensor생성 [2] torch,rand()- 

In [10]:
# 0 <= ~ <1 범위의 임의의 숫자 1개 추출 => rand
torch.manual_seed(1)

# rand(*size) : 가변인자 지정 -> 몇 차원인지 지정해줄 수 있음.
dataTS1 = torch.rand(3)
dataTS2 = torch.rand(2,3)
dataTS3 = torch.rand(2,1,3)
print(dataTS1)
print(dataTS2)
print(dataTS3)


tensor([0.7576, 0.2793, 0.4031])
tensor([[0.7347, 0.0293, 0.7999],
        [0.3971, 0.7544, 0.5695]])
tensor([[[0.4388, 0.6387, 0.5247]],

        [[0.6826, 0.3051, 0.4635]]])


- Tensor 생성 [3] torch.randn()


In [11]:
dataTS1 = torch.randn(3)
dataTS2 = torch.randn(2,3)
dataTS3 = torch.randn(2,1,3) # 정규분포 형태로 나오기 때문에 음수도 나올 수 있음.
print(dataTS1)
print(dataTS2)
print(dataTS3)

tensor([-1.8349, -2.2149,  0.0436])
tensor([[ 1.3240, -0.1005,  0.6443],
        [ 0.5244,  1.0157,  0.2571]])
tensor([[[-0.9013,  0.8138,  0.3871]],

        [[ 0.5417,  0.6646,  0.3248]]])


-Tensor 생성 [4] torch.randint()

In [130]:
dataTS1 = torch.randint(1,46,(10,6))

print(dataTS1)


tensor([[17,  9, 24,  5, 43, 22],
        [45,  5, 35, 44, 20, 34],
        [ 7, 11,  4, 34,  4, 21],
        [27, 28,  3, 39, 15, 24],
        [26, 25, 26, 45, 11, 27],
        [23, 27,  2, 37, 17, 29],
        [14, 17, 33, 15, 33, 12],
        [17, 15, 43, 28,  8,  9],
        [ 2,  4, 11, 30,  7, 28],
        [24, 26,  7, 20, 24, 40]])
