#### Tensor 이해

In [2]:
### 모듈로딩
import torch


- 타입지정 Tensor 클래스 활용
    * 데이터 타입을 설정 후 생성
    * 데이터 사이즈 설정한 텐서 생성 시
    * 데이터의 자료형 변환한 텐서 생성 시 사용

In [3]:
#### 전수형 텐서 생성
data=[1.4, 2.8, 3.1]

In [5]:
### 1바이트 정수형 텐서 생성
dataTS1 = torch.CharTensor(data)
dataTs11 = torch.tensor(data, dtype=torch.int8)

print(dataTS1, dataTs11, sep='\n')

tensor([1, 2, 3], dtype=torch.int8)
tensor([1, 2, 3], dtype=torch.int8)


C:\Users\KDP-26\AppData\Local\Temp\ipykernel_12496\3061725986.py:2: DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
  dataTS1 = torch.CharTensor(data)
C:\Users\KDP-26\AppData\Local\Temp\ipykernel_12496\3061725986.py:3: DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
  dataTs11 = torch.tensor(data, dtype=torch.int8)


In [6]:
### 2바이트 정수형 텐서 생성
dataTS1 = torch.ShortTensor(data)
dataTs11 = torch.tensor(data, dtype=torch.int16)

print(dataTS1, dataTs11, sep='\n')

tensor([1, 2, 3], dtype=torch.int16)
tensor([1, 2, 3], dtype=torch.int16)


C:\Users\KDP-26\AppData\Local\Temp\ipykernel_12496\1081463755.py:2: DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
  dataTS1 = torch.ShortTensor(data)
C:\Users\KDP-26\AppData\Local\Temp\ipykernel_12496\1081463755.py:3: DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
  dataTs11 = torch.tensor(data, dtype=torch.int16)


In [7]:
### 논리형 텐서 생성
dataTS2 = torch.BoolTensor(data)
DataTS21 = torch.tensor(data, dtype=torch.bool)
print(dataTS2, DataTS21, sep='\n')

tensor([True, True, True])
tensor([True, True, True])


In [9]:
### 실수형 텐서 생성
dataTS3 = torch.DoubleTensor(data)
dataTS31 = torch.tensor(data, dtype=torch.float64)

print(dataTS3, dataTS31, sep='\n')

tensor([1.4000, 2.8000, 3.1000], dtype=torch.float64)
tensor([1.4000, 2.8000, 3.1000], dtype=torch.float64)


- Tensor 저장소 설정 ==> 속성 device 설정

In [10]:
### 실행 위치 => CPU / GPU
DEVICE='cuda' if torch.cuda.is_available() else 'cpu'
DEVICE

'cpu'

In [11]:
### 실수형 텐서 생성
dataTS3 = torch.DoubleTensor(data)
dataTS31 = torch.tensor(data, dtype=torch.float64, device=DEVICE)

print(dataTS3, dataTS31, sep='\n')

tensor([1.4000, 2.8000, 3.1000], dtype=torch.float64)
tensor([1.4000, 2.8000, 3.1000], dtype=torch.float64)
