#### TenSor 변환

In [15]:
import torch


- Python 객체 ==> Tensor 변환
- torch.as_tensor()
    * 동일 타입과 디바이스를 가진 데이터 존재 ==> view 즉, 데이터 공유
    * 다른타입 또는 다른 디바이스를 가진 데이터 존재 ==> copy 즉, 생성
    * view tensor() 또는 copy tensor 반환

In [16]:
### List ==> Tensor
data = list(range(1, 10))
dataTS = torch.as_tensor(data, dtype=torch.int8)
print(dataTS, dataTS.shape, dataTS.ndim)


tensor([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=torch.int8) torch.Size([9]) 1


In [17]:
data[0] = 100
data, dataTS

([100, 2, 3, 4, 5, 6, 7, 8, 9],
 tensor([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=torch.int8))

- Numpy ndarray 객체 ==> Tensor 변환

In [18]:
import numpy as np

In [19]:
arr1=np.array([1,2,3])
arr1, arr1.dtype, arr1.ndim

(array([1, 2, 3]), dtype('int32'), 1)

In [20]:
arrTS=torch.as_tensor(arr1)
arrTS

tensor([1, 2, 3], dtype=torch.int32)

In [23]:
arr1[0]=99
arr1, arrTS

(array([99,  2,  3]), tensor([99,  2,  3], dtype=torch.int32))

In [24]:
# 벡터를 기준 512 이상 비트의 큰 사이즈 리스트의 tensor 변환에 적합


- Numpy ndarray ==> Tensor 변환 : from_numpy()


In [35]:
arr1 = np.array([[5,7,9],[1,2,3]], dtype=np.float32)
print(arr1, arr1.data, arr1.size, arr1.itemsize, arr1.strides)


[[5. 7. 9.]
 [1. 2. 3.]] <memory at 0x0000016934BA1040> 6 4 (12, 4)


이 코드는 `numpy` 라이브러리를 사용하여 2차원 배열을 생성하고, 그 배열의 다양한 속성들을 출력하는 예제입니다. 각 요소에 대해 자세히 설명해 드리겠습니다.

```python
arr1 = np.array([[5,7,9],[1,2,3]], dtype=np.float32)
print(arr1, arr1.data, arr1.size, arr1.itemsize, arr1.strides)
```

### 1. **`arr1 = np.array([[5,7,9],[1,2,3]], dtype=np.float32)`**

- **배열 생성**:
  - `np.array` 함수를 사용하여 2차원 배열을 생성합니다.
  - 입력 리스트 `[[5,7,9],[1,2,3]]`는 두 개의 하위 리스트를 가지며, 각각 3개의 요소를 포함하고 있습니다.
  - 결과적으로 `arr1`은 **2행 3열**의 형태를 갖는 2차원 배열이 됩니다.
- **데이터 타입 지정**:
  - `dtype=np.float32`는 배열의 요소들을 32비트 부동소수점(`float32`)으로 저장하도록 지정합니다.
  - 따라서 배열의 모든 정수 값들은 부동소수점 형태로 변환되어 저장됩니다.

**생성된 배열 `arr1`의 모습**:

```python
array([[5., 7., 9.],
       [1., 2., 3.]], dtype=float32)
```

### 2. **`print(arr1, arr1.data, arr1.size, arr1.itemsize, arr1.strides)`**

각각의 속성에 대해 설명하고, 예상되는 출력 결과를 안내해 드리겠습니다.

#### a. **`arr1`**

- **역할**:
  - 배열 자체를 출력합니다.
- **출력 내용**:
  - 배열의 요소들이 2차원 형태로 표시됩니다.
- **예상 출력**:

  ```
  [[5. 7. 9.]
   [1. 2. 3.]]
  ```

#### b. **`arr1.data`**

- **역할**:
  - 배열의 **원시 메모리 버퍼**를 나타내는 버퍼 객체를 반환합니다.
  - 배열의 데이터가 메모리 상에서 어디에 저장되어 있는지에 대한 정보를 담고 있습니다.
- **출력 내용**:
  - 메모리 버퍼 객체의 주소를 나타내는 문자열이 출력됩니다.
- **예상 출력** (주소는 실행 환경에 따라 달라질 수 있습니다):

  ```
  <memory at 0x7f8c5e3a8a00>
  ```

#### c. **`arr1.size`**

- **역할**:
  - 배열의 **전체 요소 수**를 반환합니다.
- **계산 방법**:
  - `arr1`은 2행 3열의 배열이므로, 전체 요소 수는 `2 * 3 = 6`입니다.
- **출력 내용**:

  ```
  6
  ```

#### d. **`arr1.itemsize`**

- **역할**:
  - 배열의 **각 요소의 메모리 크기(바이트 단위)**를 반환합니다.
- **계산 방법**:
  - `dtype`이 `float32`이므로, 각 요소는 `4`바이트를 차지합니다 (32비트 = 4바이트).
- **출력 내용**:

  ```
  4
  ```

#### e. **`arr1.strides`**

- **역할**:
  - 배열의 각 차원에서 다음 요소로 이동하기 위해 건너뛰어야 하는 **바이트 수**를 나타내는 튜플을 반환합니다.
- **계산 방법**:
  - 첫 번째 값은 **행(row) 방향**으로 한 행을 넘어가기 위해 건너뛰어야 하는 바이트 수입니다.
    - 계산: `arr1.shape[1] * arr1.itemsize = 3 * 4 = 12`바이트
  - 두 번째 값은 **열(column) 방향**으로 한 열을 넘어가기 위해 건너뛰어야 하는 바이트 수입니다.
    - 계산: `arr1.itemsize = 4`바이트
- **출력 내용**:

  ```
  (12, 4)
  ```

### 3. **전체 출력 예시**

```python
[[5. 7. 9.]
 [1. 2. 3.]] <memory at 0x7f8c5e3a8a00> 6 4 (12, 4)
```

- **주의**: `<memory at 0x7f8c5e3a8a00>` 부분의 메모리 주소는 실행 환경에 따라 달라질 수 있습니다.

### 4. **추가 설명**

#### **`arr1.strides` 상세 설명**

- **`strides`**:
  - `strides`는 배열의 각 차원에서 다음 요소로 이동하기 위해 건너뛰어야 하는 바이트 수를 나타냅니다.
  - `arr1.strides`가 `(12, 4)`인 경우:
    - **첫 번째 차원(행)**:
      - 한 행의 모든 요소를 건너뛰기 위해서는 `12`바이트를 이동해야 합니다.
      - 이는 한 행에 있는 전체 요소의 메모리 크기입니다 (`3`요소 * `4`바이트).
    - **두 번째 차원(열)**:
      - 다음 열로 이동하기 위해서는 `4`바이트를 이동해야 합니다.
      - 이는 각 요소의 메모리 크기입니다.

#### **메모리 상에서의 배열 배치**

- **메모리 구조**:
  - `numpy`는 기본적으로 C-스타일의 **행 우선(row-major) 순서**로 배열을 저장합니다.
  - 이는 메모리에서 행의 요소들이 연속적으로 저장된다는 의미입니다.

- **메모리 주소 예시**:

  | 메모리 주소 | 배열 요소 | 값    |
  |-------------|-----------|-------|
  | 0           | `arr1[0,0]` | `5.0` |
  | 4           | `arr1[0,1]` | `7.0` |
  | 8           | `arr1[0,2]` | `9.0` |
  | 12          | `arr1[1,0]` | `1.0` |
  | 16          | `arr1[1,1]` | `2.0` |
  | 20          | `arr1[1,2]` | `3.0` |

  - 각 요소는 `4`바이트를 차지하며, 행을 넘어갈 때는 `12`바이트(한 행의 전체 크기)를 건너뜁니다.

### 5. **요약**

- **`arr1`**: 생성된 `numpy` 배열로, `[ [5.0, 7.0, 9.0], [1.0, 2.0, 3.0] ]`의 값을 가집니다.
- **`arr1.data`**: 배열의 원시 메모리 버퍼를 나타내는 객체입니다.
- **`arr1.size`**: 배열의 총 요소 수로, 이 예제에서는 `6`입니다.
- **`arr1.itemsize`**: 배열의 각 요소가 차지하는 메모리 크기로, `float32` 타입이므로 `4`바이트입니다.
- **`arr1.strides`**: 배열의 각 차원에서 다음 요소로 이동하기 위해 건너뛰어야 하는 바이트 수로, `(12, 4)`입니다.

---

이렇게 코드의 각 요소와 그 의미에 대해 상세히 설명해 드렸습니다. 추가로 궁금한 사항이나 더 알고 싶은 내용이 있으시면 언제든지 질문해 주세요!

In [37]:
arrTS=torch.from_numpy(arr1)
arrTS

tensor([[5., 7., 9.],
        [1., 2., 3.]])

In [38]:
# 데이터 공유 sharing
# touch.as_tensor()
# touch.from_numpy()

# 데이터 복사 Copy
# touch.tensor()
# touch.Tensor()


In [ ]:
# 형변환 Type Casting

