#### Tensor 이해 - 형변환

In [9]:
import torch
import numpy as np

In [10]:
# 방법 1 type(torch.XXXX)
dataTS1 = torch.tensor([1,3,5])
dataTS1, dataTS1.dtype

(tensor([1, 3, 5]), torch.int64)

In [11]:
# int 64 -> float
dataTS11=dataTS1.type(torch.float32)
dataTS11, dataTS11.dtype

(tensor([1., 3., 5.]), torch.float32)

- 방법 [2] 타입명()

In [13]:
# int 64 -> float
dataTS11 = dataTS1.float()
dataTS11, dataTS11.dtype

(tensor([1., 3., 5.]), torch.float32)

In [14]:
dataTS1.bool()

tensor([True, True, True])

- 방법[3] to(dtype=000, device=000)

In [17]:
# int 64 -> bool
dataTS1.to(dtype=torch.int8, device='cuda' if torch.cuda.is_available() else 'cpu')

tensor([1, 3, 5], dtype=torch.int8)