### Tensor의 모양/형태/shape 변경과 View Tensor


In [9]:
### 모듈 로딩
import torch
import numpy as np

In [20]:
## 텐서 생성
dataTS=torch.arange(1, 21)
print(dataTS, dataTS.ndim, dataTS.stride(), sep='\n')
print(dataTS.storage())
print(f'is_contiguous() : {dataTS.is_contiguous()}') # 연속성 여부 확인

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
        19, 20])
1
(1,)
 1
 2
 3
 4
 5
 6
 7
 8
 9
 10
 11
 12
 13
 14
 15
 16
 17
 18
 19
 20
[torch.storage.TypedStorage(dtype=torch.int64, device=cpu) of size 20]
is_contiguous() : True


In [19]:
# 1D => 2D 형태/모양/shape 변경
dataTS2=dataTS.reshape((-1, 5))
print(dataTS2, dataTS2.ndim, dataTS2.stride(), sep='\n')
print(dataTS2.storage())
print(f'is_contiguous() : {dataTS2.is_contiguous()}') # 연속성 여부 확인

tensor([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20]])
2
(5, 1)
 1
 2
 3
 4
 5
 6
 7
 8
 9
 10
 11
 12
 13
 14
 15
 16
 17
 18
 19
 20
[torch.storage.TypedStorage(dtype=torch.int64, device=cpu) of size 20]
is_contiguous() : True


In [16]:
dataTS2[0][0]=77

In [17]:
dataTS, dataTS2

(tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
         19, 20]),
 tensor([[77,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10],
         [11, 12, 13, 14, 15],
         [16, 17, 18, 19, 20]]))

In [21]:
dataTS22=dataTS2.reshape((-1, 2))
print(dataTS22, dataTS22.ndim, dataTS22.stride(), sep='\n')
print(dataTS22.storage())
print(f'is_contiguous() : {dataTS22.is_contiguous()}')

tensor([[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10],
        [11, 12],
        [13, 14],
        [15, 16],
        [17, 18],
        [19, 20]])
2
(2, 1)
 1
 2
 3
 4
 5
 6
 7
 8
 9
 10
 11
 12
 13
 14
 15
 16
 17
 18
 19
 20
[torch.storage.TypedStorage(dtype=torch.int64, device=cpu) of size 20]
is_contiguous() : True


In [28]:
dataTS23=dataTS22.T
dataTS23, dataTS23.is_contiguous()

(tensor([[ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19],
         [ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20]]),
 False)

In [31]:
## 불연속적 ==> 연속적으로 저장되도록 하기
dTS=dataTS23.contiguous()
dTS

tensor([[ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19],
        [ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20]])

In [32]:
dTS.storage()

 1
 3
 5
 7
 9
 11
 13
 15
 17
 19
 2
 4
 6
 8
 10
 12
 14
 16
 18
 20
[torch.storage.TypedStorage(dtype=torch.int64, device=cpu) of size 20]